[package]
name = "wfpoa"
version = "0.1.0"
authors = ["AndreaGuarracino <andreaguarracino@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
opt-level = 3

[dependencies]
